apiVersion: v1
kind: Service
metadata:
  name: nanopaperwallet-offline
  namespace: nanopaperwallet
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: app
  selector:
    app: nanopaperwallet-offline