apiVersion: v1
kind: Service
metadata:
  name: nanopaperwallet
  namespace: nanopaperwallet
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: app
  selector:
    app: nanopaperwallet-app
